In [19]:
import pandas as pd
import os

In [20]:
for file in os.listdir('.'):
    if 'xlsx' in file and '$' not in file:
        file_excel = file

In [21]:
data = pd.read_excel(file_excel, sheet_name='Лист2', usecols='A:B', names=['наименование', 'цена'])

data = data.fillna('')
data = data[data['наименование'] != '']

data

                                         наименование     цена
0                             МЦ Династия на Репищева
2               Первичная консультация нейрофизиолога  1200 р.
3                               МЦ Династия на Ленина
5               Первичная консультация нейрофизиолога  1200 р.
6               Деликатная терапия души на Жуковского
8               Первичная консультация нейрофизиолога  1200 р.
9                          МЦ Династия во Всеволожске
11              Первичная консультация нейрофизиолога  1200 р.
12              МЦ Светофор на проспекте Луначарского
14  Консультативный приём врача высшей категории, ...  1600 р.
15                Деликатная терапия души на Репищева
17              Первичная консультация нейрофизиолога  1200 р.

In [22]:
dct = {'Центр' : [],
      'Услуга' : [], 
      'Цена' : []}

for i in data.index:
    if data['цена'][i] == '':
        temp_centr = data['наименование'][i]
        continue
    dct['Центр'].append(temp_centr)
    dct['Услуга'].append(data['наименование'][i])
    dct['Цена'].append(data['цена'][i])

In [23]:
data_new  = pd.DataFrame(dct)


data_new

,Центр,Услуга,Цена
0,МЦ Династия на Репищева,Первичная консультация нейрофизиолога,1200 р.
1,МЦ Династия на Ленина,Первичная консультация нейрофизиолога,1200 р.
2,Деликатная терапия души на Жуковского,Первичная консультация нейрофизиолога,1200 р.
3,МЦ Династия во Всеволожске,Первичная консультация нейрофизиолога,1200 р.
4,МЦ Светофор на проспекте Луначарского,"Консультативный приём врача высшей категории, ...",1600 р.
5,Деликатная терапия души на Репищева,Первичная консультация нейрофизиолога,1200 р.

In [24]:
data_new['Центр'] = data_new['Центр'].apply(lambda x: x[:x.find(' на ')])
data_new['Цена'] = data_new['Цена'].apply(lambda x: int(x[:x.find(' р')]))

In [26]:
data_new = data_new.drop_duplicates(subset=['Центр', 'Услуга'])

data_new.to_excel('цены_' + file_excel, index=False)