In [15]:
import pandas as pd
import os

In [16]:
for file in os.listdir('.'):
    if 'xlsx' in file and '$' not in file:
        file_excel = file

In [17]:
data = pd.read_excel(file_excel, sheet_name='Лист2', usecols='A:B', names=['наименование', 'цена'], header=None)

data = data.fillna('')
data = data[data['наименование'] != '']

data

                                          наименование     цена
0                              МЦ Династия на Репищева
2    Удаление доброкачественных образований полости...  3200 р.
3               Энергия Здоровья на проспекте Энгельса
5    Удаление доброкачественных новообразований ЛОР...  3800 р.
6                       САН Клиник в Шведском переулке
..                                                 ...      ...
359  Удаление доброкачественного новообразования на...  8100 р.
360        ЛДЦ МИБС им. С.М. Березина на 6-й Советской
362  Удаление доброкачественного образования наружн...  4500 р.
363              ЛДЦ МИБС им. С.М. Березина на Есенина
365  Удаление доброкачественного образования наружн...  4500 р.

[244 rows x 2 columns]

In [18]:
dct = {'Центр' : [],
      'Услуга' : [], 
      'Цена' : []}

for i in data.index:
    if data['цена'][i] == '':
        temp_centr = data['наименование'][i]
        continue
    dct['Центр'].append(temp_centr)
    dct['Услуга'].append(data['наименование'][i])
    dct['Цена'].append(data['цена'][i])

In [19]:
data_new  = pd.DataFrame(dct)


data_new

,Центр,Услуга,Цена
0,МЦ Династия на Репищева,Удаление доброкачественных образований полости...,3200 р.
1,Энергия Здоровья на проспекте Энгельса,Удаление доброкачественных новообразований ЛОР...,3800 р.
2,САН Клиник в Шведском переулке,Удаление доброкачественных новообразований лор...,10920 р.
3,МЦ Династия на Ленина,Удаление доброкачественных образований полости...,3200 р.
4,Медика на Бадаева,Удаление доброкачественных новообразований из ...,1700 р.
...,...,...,...
117,СПГМУ им. И.П. Павлова,Оперативное лечение новообразований уха Гистол...,37300 р.
118,ФГБУ КДЦ с поликлиникой,Удаление атеромы наружного уха (2),5000 р.
119,Ленинградская областная клиническая больница,Удаление доброкачественного новообразования на...,8100 р.
120,ЛДЦ МИБС им. С.М. Березина на 6-й Советской,Удаление доброкачественного образования наружн...,4500 р.
121,ЛДЦ МИБС им. С.М. Березина на Есенина,Удаление доброкачественного образования наружн...,4500 р.

In [20]:
def no_suffix(x):
    if ' на ' in x:
        return x[:x.find(' на ')]
    elif ' в ' in x:
        return x[:x.find(' в ')]
    else:
        return x

data_new['Центр'] = data_new['Центр'].apply(no_suffix)
data_new['Цена'] = data_new['Цена'].apply(lambda x: int(x[:x.find(' р')]))

In [21]:
data_new = data_new.drop_duplicates(subset=['Центр', 'Услуга'])

data_new[['Центр', 'Цена', 'Услуга']].to_excel('цены_' + file_excel, index=False)