In [3]:
import pandas as pd
import os

In [4]:
os.listdir('.')

['.ipynb_checkpoints',
 'cist.ipynb',
 '~$Цистоуретроскопия_с_анестезией.xlsx',
 'Цистоуретроскопия_с_анестезией.xlsx']

In [5]:
data = pd.read_excel('Цистоуретроскопия_с_анестезией.xlsx', sheet_name='Лист2')

data = data.fillna('')
data

                                        наименование     цена
0                            МЦ Династия на Репищева
1                                        Цистоскопия  5000 р.
2     Клиника Благодатная на проспекте Юрия Гагарина
3                             Цистоскопия для женщин  2000 р.
4              МЦ Запад-Восток на Шкиперской протоке
..                                               ...      ...
402                      Цистоскопия диагностическая  1300 р.
403    Областной онкодиспансер на Литейном проспекте
404                             Цистоскопия у женщин    40 р.
405  Областной онкодиспансер в поселке Кузьмоловский
406                             Цистоскопия у женщин    40 р.

[407 rows x 2 columns]

In [6]:
dct = {'Центр' : [],
      'Услуга' : [], 
      'Цена' : []}

for i in data.index:
    if data['цена'][i] == '':
        temp_centr = data['наименование'][i]
        continue
    dct['Центр'].append(temp_centr)
    dct['Услуга'].append(data['наименование'][i])
    dct['Цена'].append(data['цена'][i])

In [7]:
data_new  = pd.DataFrame(dct)


data_new

,Центр,Услуга,Цена
0,МЦ Династия на Репищева,Цистоскопия,5000 р.
1,Клиника Благодатная на проспекте Юрия Гагарина,Цистоскопия для женщин,2000 р.
2,МЦ Запад-Восток на Шкиперской протоке,Цистоскопия,4500 р.
3,ЭкспертЪ на Пионерской,"Цитологическое исследование материала, получен...",860 р.
4,Мединеф на Боткинской,Цистоскопия без биопсии у женщин,2000 р.
...,...,...,...
209,НИИ онкологии им. Н.Н. Петрова,КДО: Цистоскопия диагностическая,1300 р.
210,КДЦ НИИ онкологии им. Н.Н. Петрова,Цистоскопия лечебно-диагностическая,2000 р.
211,КДЦ НИИ онкологии им. Н.Н. Петрова,Цистоскопия диагностическая,1300 р.
212,Областной онкодиспансер на Литейном проспекте,Цистоскопия у женщин,40 р.
213,Областной онкодиспансер в поселке Кузьмоловский,Цистоскопия у женщин,40 р.

In [8]:
data_new['Центр'] = data_new['Центр'].apply(lambda x: x[:x.find(' на ')])
data_new['Цена'] = data_new['Цена'].apply(lambda x: int(x[:x.find(' р')]))

In [9]:
data_new

,Центр,Услуга,Цена
0,МЦ Династия,Цистоскопия,5000
1,Клиника Благодатная,Цистоскопия для женщин,2000
2,МЦ Запад-Восток,Цистоскопия,4500
3,ЭкспертЪ,"Цитологическое исследование материала, получен...",860
4,Мединеф,Цистоскопия без биопсии у женщин,2000
...,...,...,...
209,НИИ онкологии им. Н.Н. Петров,КДО: Цистоскопия диагностическая,1300
210,КДЦ НИИ онкологии им. Н.Н. Петров,Цистоскопия лечебно-диагностическая,2000
211,КДЦ НИИ онкологии им. Н.Н. Петров,Цистоскопия диагностическая,1300
212,Областной онкодиспансер,Цистоскопия у женщин,40
213,Областной онкодиспансер в поселке Кузьмоловски,Цистоскопия у женщин,40

In [10]:
data_new['обезбол'] = data_new['Услуга'].apply(lambda x: any([i in x.lower() for i in ('обезбол', 'анестез', 'нарко')]))

In [14]:
data_new[data_new['обезбол'] == True].to_excel('цены.xlsx')