In [16]:
import pandas as pd
import datetime

In [17]:
base = pd.read_excel('СПУ_1.xlsx')

In [18]:
base = base.append(pd.read_excel('СПУ_2.xlsx'))
base

,Номер карты,СПУ из карточки Пациента,Дата начала СПУ из карточки Пациента,Дата окончания СПУ из карточки Пациента,ISNULL([СПУ из карточки Пациента])
0,5,ПППК 10%,2017-08-17,2017-08-18 00:00:00,0
1,8,ПППК 10%,2014-02-24,-,0
2,39,ПО ВОЗРАСТУ 75+ 10%,2019-05-30,-,0
3,47,ПППК 5%,2013-03-29,-,0
4,49,ПО ВОЗРАСТУ 75+ 10%,2019-05-30,-,0
...,...,...,...,...,...
250,990357860,-,2016-04-22,-,-1
251,990366697,-,2016-07-28,-,-1
252,990368063,-,2016-10-15,-,-1
253,990368968,-,2016-10-29,-,-1
254,990370152,-,2017-01-05,-,-1

In [19]:
base = base.reset_index(drop=True)

In [20]:
def get_date(x):
    try:
        x = x.date()
        return x
    except:
        return x
    

base['Дата окончания СПУ из карточки Пациента'] = base['Дата окончания СПУ из карточки Пациента'].apply(get_date)

In [24]:
base

,Номер карты,СПУ из карточки Пациента,Дата начала СПУ из карточки Пациента,Дата окончания СПУ из карточки Пациента,ISNULL([СПУ из карточки Пациента])
0,5,ПППК 10%,2017-08-17,2017-08-18,0
1,8,ПППК 10%,2014-02-24,-,0
2,39,ПО ВОЗРАСТУ 75+ 10%,2019-05-30,-,0
3,47,ПППК 5%,2013-03-29,-,0
4,49,ПО ВОЗРАСТУ 75+ 10%,2019-05-30,-,0
...,...,...,...,...,...
213211,990357860,-,2016-04-22,-,-1
213212,990366697,-,2016-07-28,-,-1
213213,990368063,-,2016-10-15,-,-1
213214,990368968,-,2016-10-29,-,-1
213215,990370152,-,2017-01-05,-,-1

In [25]:
base_end = base[base['Дата окончания СПУ из карточки Пациента'] == '-']

In [26]:
base_end

,Номер карты,СПУ из карточки Пациента,Дата начала СПУ из карточки Пациента,Дата окончания СПУ из карточки Пациента,ISNULL([СПУ из карточки Пациента])
1,8,ПППК 10%,2014-02-24,-,0
2,39,ПО ВОЗРАСТУ 75+ 10%,2019-05-30,-,0
3,47,ПППК 5%,2013-03-29,-,0
4,49,ПО ВОЗРАСТУ 75+ 10%,2019-05-30,-,0
5,55,ПППК 5%,2018-07-26,-,0
...,...,...,...,...,...
213211,990357860,-,2016-04-22,-,-1
213212,990366697,-,2016-07-28,-,-1
213213,990368063,-,2016-10-15,-,-1
213214,990368968,-,2016-10-29,-,-1
213215,990370152,-,2017-01-05,-,-1

In [34]:
temp = base[base['Дата окончания СПУ из карточки Пациента'] != '-']

In [37]:
base_end = base_end.append(temp[temp['Дата окончания СПУ из карточки Пациента'] >= datetime.date(2020,9,24)])

In [38]:
base_end = base_end.reset_index(drop=True)

In [42]:
base_end['Дата начала СПУ из карточки Пациента']  = base_end['Дата начала СПУ из карточки Пациента'].apply(get_date)

In [48]:
base_end_new = base_end[base_end['Дата начала СПУ из карточки Пациента'] <= datetime.date(2020,9,24)]

In [51]:
group_base_end_new = base_end_new.groupby('Номер карты', as_index=False).agg({'СПУ из карточки Пациента':list})

In [52]:
group_base_end_new

       Номер карты                           СПУ из карточки Пациента
0                8                                         [ПППК 10%]
1               39                              [ПО ВОЗРАСТУ 75+ 10%]
2               47                                         [ПППК  5%]
3               49                              [ПО ВОЗРАСТУ 75+ 10%]
4               55                                         [ПППК  5%]
...            ...                                                ...
161971   990523879                              [ПО ВОЗРАСТУ 75+ 10%]
161972   990523880                              [ПО ВОЗРАСТУ 75+ 10%]
161973  1200277529                                         [ПППК 10%]
161974  1400022031                                   [XXI век Друзья]
161975           -  [Друзья 25%, Друзья 25%, Друзья 25%, ПО ВОЗРАС...

[161976 rows x 2 columns]

In [54]:
data = pd.read_excel('Ошибки ПППК на 21.09.2020.xlsx')

In [56]:
data['Номер карты'].nunique()

6202

In [63]:
data = data.merge(group_base_end_new, how='left', left_on='Номер карты', right_on='Номер карты')

In [65]:
data.to_excel('Сравнение.xlsx')