In [1]:
import pandas as pd
import os

In [2]:
for file in os.listdir('.'):
    if 'xlsx' in file and '$' not in file:
        file_excel = file

In [3]:
data = pd.read_excel(file_excel, sheet_name='Лист2', usecols='A:B', names=['наименование', 'цена'], header=None)

data = data.fillna('')
data = data[data['наименование'] != '']

data

                                          наименование      цена
0                        Долголетие на Малой Посадской
2                   Лапороскопическое низведение яичка  25000 р.
3    Эндопротезирование яичка (имплантация искусств...  18000 р.
4                        Двухсторонняя энулеация яичек  19000 р.
5                                ИнтраМед на Савушкина
..                                                 ...       ...
271    ДГБ № 2 Св. Марии Магдалины на 2-ой линии В. О.
273                                   Низведение яичка  29040 р.
274     Городская больница Святого Георгия на Северном
276                                        Орхиэктомия  20500 р.
277  Пластика оболочек яичек (Протезирование яичка ...  18500 р.

[215 rows x 2 columns]

In [4]:
dct = {'Центр' : [],
      'Услуга' : [], 
      'Цена' : []}

for i in data.index:
    if data['цена'][i] == '':
        temp_centr = data['наименование'][i]
        continue
    dct['Центр'].append(temp_centr)
    dct['Услуга'].append(data['наименование'][i])
    dct['Цена'].append(data['цена'][i])

In [5]:
data_new  = pd.DataFrame(dct)


data_new

,Центр,Услуга,Цена
0,Долголетие на Малой Посадской,Лапороскопическое низведение яичка,25000 р.
1,Долголетие на Малой Посадской,Эндопротезирование яичка (имплантация искусств...,18000 р.
2,Долголетие на Малой Посадской,Двухсторонняя энулеация яичек,19000 р.
3,ИнтраМед на Савушкина,Орхэктомия - удаление яичка (односторонняя),13000 р.
4,ИнтраМед на Савушкина,Орхэктомия - удаление яичка (двухсторонняя),19600 р.
...,...,...,...
145,Клиника им. Э.Э.Эйхвальда,"Орхиэктомия (удаление яичка), с лимфаденэктомией",9000 р.
146,НИИ онкологии им. Н.Н. Петрова,КДО: Двухсторонняя орхиэктомия,9000 р.
147,ДГБ № 2 Св. Марии Магдалины на 2-ой линии В. О.,Низведение яичка,29040 р.
148,Городская больница Святого Георгия на Северном,Орхиэктомия,20500 р.
149,Городская больница Святого Георгия на Северном,Пластика оболочек яичек (Протезирование яичка ...,18500 р.

In [6]:
def no_suffix(x):
    if ' на ' in x:
        return x[:x.find(' на ')]
    elif ' в ' in x:
        return x[:x.find(' в ')]
    else:
        return x

data_new['Центр'] = data_new['Центр'].apply(no_suffix)
data_new['Цена'] = data_new['Цена'].apply(lambda x: int(x[:x.find(' р')]))

In [7]:
data_new = data_new.drop_duplicates(subset=['Центр', 'Услуга'])

data_new.to_excel('цены_' + file_excel, index=False)